server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 192.168.154.129:8848
    gateway:
      routes:
        - id: item-service
          uri: lb://item-service
          predicates:
            - path=/items/**